package constant

const ID = "id"
const UserId = "userId"
const VideoID = "video_id"
const CommentText = "comment_text"
const CommentCreateDate = "create_date"
const FollowerId = "follower_id"
const LikeDate = "like_date"
const UserName = "username"
const PassWord = "password"
const AuthorId = "author_id"
const PlayURL = "play_url"
const CoverURL = "cover_url"
const PublishTime = "publish_time"
const Title = "title"

const USER = "users"
const LIKE = "likes"
const COMMENT = "comments"
const VIDEO = "videos"
const FOLLOW = "follows"
